#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE ${POSTGRES_DEX_DATABASE};
	CREATE USER ${POSTGRES_DEX_USER} WITH PASSWORD '${POSTGRES_DEX_PASSWORD}';
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DEX_DATABASE} TO dex;

	CREATE DATABASE ${POSTGRES_DBOXED_DATABASE};
  CREATE USER ${POSTGRES_DBOXED_USER} WITH PASSWORD '${POSTGRES_DBOXED_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DBOXED_DATABASE} TO dex;
EOSQL
